create table if not exists leads (
  id uuid primary key,
  task_id uuid null,
  company_name text not null,
  legal_name text,
  activity text,
  category text,
  investment_type text,
  website text,
  domain text,
  contact_email text,
  phone text,
  address text,
  city text,
  postal_code text,
  country text,
  ceo text,
  contact_person text,
  role text,
  linkedin text,
  uid_vat text,
  commercial_register text,
  employees integer,
  revenue numeric,
  capital_need boolean,
  capital_need_text text,
  estimated_ticket_size numeric,
  source text,
  sources jsonb default '[]'::jsonb,
  quality_score integer default 0,
  investment_score integer default 0,
  duplicate_key text unique,
  status text,
  tags jsonb default '[]'::jsonb,
  notes text,
  created_at timestamptz,
  updated_at timestamptz,
  last_verified timestamptz
);

create table if not exists search_tasks (
  id uuid primary key,
  raw_query text not null,
  country text,
  region text,
  language text,
  category text,
  investment_type text,
  budget_min numeric,
  budget_max numeric,
  goal text,
  auto_agents boolean default true,
  status text,
  notes text,
  created_at timestamptz
);

create table if not exists email_drafts (
  id uuid primary key,
  lead_id uuid null,
  to_email text,
  subject text not null,
  body text not null,
  language text,
  approved boolean default false,
  sent boolean default false,
  created_at timestamptz
);
